#Version del docker compose
version: "3.3"

services:
    nginx-front:
        #Contenedor del Frontend de la aplicación, NO ejecuta código de backend
        build: 
            context: .
            args: 
                - config=desarrollo
        container_name: nginx_front
        restart: always
        volumes:
            # Los archivos del front deben copiarse en la carpeta /frontend
            #- ./site:/app
            #- ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
            - ./logs/front/nginx-error.log:/var/log/nginx/error.log
            - ./logs/front/nginx-access.log:/var/log/nginx/access.log
        ports:   
            - 80:80
        networks:
            - webnet            

networks:
    webnet:            