export interface EmpresaCompras {
    IdComprasEmpresa? :any, 
    nombre_empresa? :any, 
	rif? :any, 
	nit? :any, 
	fecha_ejercicio_desde? :any, 
	fecha_ejercicio_hasta? :any, 
	tipo_depreciacion? :any, 
	genera_comprobante_automaticos? :any, 
	separador_cod_contables? :any, 
	Formato_cod_contable? :any, 
	fecha_fija_movimientos? :any, 
	Maneja_proveedores_admin? :any, 
	maneja_clientes_admin? :any, 
	base_de_datos? :any, 
	fecha_ope? :any, 
	logo? :any, 
	cerrada? :any,
    direccion_fiscal? : any,
}

