export interface MovimientoAlmacen {
    alma_mov_inv_id?,
    alma_mov_inv_tipo?,
    alma_mov_inv_id_producto?,
    alma_mov_inv_id_cantidad?,
    alma_mov_inv_entrada?,
    alma_mov_inv_salida?,
    alma_mov_inv_id_almacen_origen?,
    alma_mov_inv_id_almacen_destino?,
    alma_mov_inv_id_usuario_proceso?,
    alma_mov_inv_id_usuario_aprobo?,
    alma_mov_inv_fecha_solicitud?,
    alma_mov_inv_fecha_aprobacion?,
    alma_mov_inv_aprobado?,
    alma_mov_inv_id_activo?,
    alma_mov_inv_es_logico?,
    alma_mov_inv_costo?,
    alma_mov_inv_costo_Dollar?,
    alma_mov_inv_id_puesto?,
    alma_mov_inv_id_oc?,
    alma_mov_inv_lote?,
    alma_mov_inv_justificacion?,
    alma_mov_inv_rif_empresa?,
    alma_mov_inv_fecha_caducidad?,
    alm_mov_estatus?,

    
}