export interface detalleOcModelo {
    idOcDetalle?, 
	codigo?, 
	nombre?, 
	descripcion?, 
	unidadMedidaC?, 
	cantidad?, 
	idAdmActivo?, 
	fechaAlta?, 
	fechaRequerida?, 
	justificacion?, 
	IdComprasEmpresa?, 
	idGenAreaNegocio?, 
	idGenCentroCostos?, 
	idComprasOC?, 
	idAreaTrabajo?, 
	cant_encontrada?, 
	cant_recibido?,
	cant_conforme?,
	precio?, 
	idProveedor?, 
	notas?,
	precio_neto?,
	tasa_iva?,
	subtotal? :number,
	precio_usd? : number,
	precio_usd_sutotal? : number,
}