export interface recepcion_detalle {
    alma_mov_inv_id ?, 
    tipo ?, 
    id_producto ?, 
    entrada ?, 
    salida ?, 
    id_almacen_origen ?, 
    id_almacen_destino ?, 
    id_usuario_proceso ?, 
    id_usuario_aprobo ?, 
    fecha_solicitud ?, 
    fecha_aprobacion ?, 
    aprobado ?, 
    id_activo ?, 
    es_logico ?, 
    costo ?, 
    costo_Dollar ?, 
    id_puesto ?, 
    id_oc ?, 
    lote ?, 
    justificacion ?, 
    rif_empresa ?, 
    fecha_caducidad ?, 
    estatus? 
}