export interface TicketServicio {
    idTicketServicio?,
    fechaAlta?,
    descripcion?,
    fechaRequerida?,
    fechaEstimada?,
    idEstadoActual? : number,
    estadoActual?,
    fechaEstadoActual?,
    justificacionEstadoActual?,
    idGerenciaOrigen?, 
    gerenciaOrigen?,
    idGerenciaDestino?,
    gerenciaDestino?,
    idSegUsuario?,
    idServiciosGerencias?,
    idAssets?,
    idSegUsuarioOrigen?,
    estado_actual_accion_adic?,
    tipo_servicio?
    idSegUsuarioAsignado?,
    nombre_asignado?,
    idSolpedCompras? : number,
}